name: CI Workflow
description: 'Shared CI workflow.'
inputs:
  run_tests:
    description: 'If true, run unit tests, otherwise skip them.'
    required: false
    default: 'true'
  java_version:
    description: 'The Java version to use.'
    required: true
  java_distribution:
    description: 'The Java distribution to use.'
    required: false
    default: 'temurin'

runs:
  using: composite
  steps:
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: ${{ inputs.java_distribution }}
        java-version: ${{ inputs.java_version }}
        
    - name: Restore dependencies
      shell: bash
      id: restore
      run: ./gradlew dependencies

    - name: Build
      shell: bash
      id: build
      run: ./gradlew jar

    - name: Run Tests
      if: steps.build.outcome == 'success' && inputs.run_tests == 'true'
      shell: bash
      run: ./gradlew test
