name: Manual Publish Documentation
on:
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: read # No OIDC needed.
      contents: write # For publishing documentation.
    steps:
      - uses: actions/checkout@v4

      - name: CI check
        uses: ./.github/actions/ci
        with:
          run_tests: 'false'
          java_version: '11'

      - uses: launchdarkly/gh-actions/actions/publish-pages@publish-pages-v1.0.1
        name: 'Publish to Github pages'
        with:
          docs_path: build/docs/javadoc
          github_token: ${{ secrets.GITHUB_TOKEN }}
